baseURL = "https://www.copyrightexceptions.eu/v2dev/"
languageCode = "en-us"
title = "Copyright Exceptions"
theme = "copex"

[taxonomies]
  exception = "exceptions"
  memberstate = "memberstates"
  alldata = "alldata"
