baseURL = "https://www.copyrightexceptions.eu/v2dev/"
languageCode = "en-us"
title = "Copyright Exceptions"
theme = "copex"

[outputs]
  home = ["HTML", "RSS", "JSON"]

[taxonomies]
  exception = "exceptions"
  memberstate = "memberstates"